version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - APP_HOST = localhost
      - APP_PORT = 3001
      - MONGODB_CONNECTION_STRING = mongodb://localhost:27017/video_sharing_app
      - TYPEORM_AUTO_SYNC_SCHEMA_DATABASE = false
      - YOUTUBE_API_URL = https://youtube.googleapis.com/youtube/v3
      - YOUTUBE_API_KEY = AIzaSyD91XkobCc2UmxihZI4GQcm3Qc4u8QNxQM
      - JWT_ACCESS_TOKEN_SECRET = your-secret-key
      - JWT_TOKEN_EXPIRES_IN = 1h
    network_mode: "host"
    depends_on:
      - mongodb
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - NEXT_PUBLIC_API_END_POINT=http://localhost:3001
  mongodb:
    image: mongo
    network_mode: "host"
    volumes:
      - ./data:/data/db
